### ISSUE TITLE
Integrate to UNIQUES-Plugin

### ISSUE THREAD

**Issue by MysticJay** [c-schmitz/iitc-unique-export#4]
Hi, are there any objections to integrate the code to the main UNIQUES plugin?

**Comment by c-schmitz** [comment]
No objection - feel free.

**Comment by MysticJay** [comment]
Great thanks. Code will be added to UNIQUES after build 0.3.0 has gone RTM.

**Comment by MysticJay** [comment]
It has been added to https://github.com/IITC-CE/ingress-intel-total-conversion/pull/388.
But in favor of writing and reading a file directly the Copy-Paste-Screen was dropped.
If anyone misses that procedure, let me know.
